name: Dev - Apply
on: [workflow_dispatch]
jobs:
  TerraformApply:
#    runs-on: self-hosted
    runs-on: ubuntu-latest
    env:
      vault_token: ${{ secrets.vault_token }}
    steps:
      - uses: actions/checkout@v4
      - name: Import Secrets
        id: import-secrets
        uses: hashicorp/vault-action@v2
        with:
          url: http://vault.yourtherapist.in:8200/
          token: ${{ secrets.vault_token }}
          secrets: |
            kv/data/azuresecrets ARM_CLIENT_ID | ARM_CLIENT_ID ;
            kv/data/azuresecrets ARM_CLIENT_SECRET | ARM_CLIENT_SECRET ;
            kv/data/azuresecrets ARM_TENANT_ID | ARM_TENANT_ID ;
            kv/data/azuresecrets ARM_SUBSCRIPTION_ID | ARM_SUBSCRIPTION_ID ;
      - name: Terraform Apply
        run: |
          export ARM_CLIENT_ID="${{ env.ARM_CLIENT_ID }}"
          export ARM_CLIENT_SECRET="${{ env.ARM_CLIENT_SECRET }}"
          export ARM_TENANT_ID="${{ env.ARM_TENANT_ID }}"
          export ARM_SUBSCRIPTION_ID="${{ env.ARM_SUBSCRIPTION_ID }}"
          az login --service-principal --username $ARM_CLIENT_ID --password $ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID
          make dev-apply token=${vault_token}
